export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'


export const LOAD_PLAYERS_REQUEST = 'LOAD_PLAYERS_REQUEST'
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS'
export const LOAD_PLAYERS_FAIL    = 'LOAD_PLAYERS_FAIL'
